// Auto-generated by export_w8a8.py — do not edit
#pragma once
#include <stdint.h>

#define DSCNN_N_CLASSES   4
#define DSCNN_N_MELS      30
#define DSCNN_FILTERS     172
#define DSCNN_N_BLOCKS    4
#define DSCNN_SAMPLE_RATE 3333
#define DSCNN_N_FFT       133
#define DSCNN_HOP         66
#define DSCNN_WINDOW_SAMPLES 6666
#define DSCNN_STEM_STRIDE_H 4
#define DSCNN_STEM_STRIDE_W 2
#define DSCNN_STEM_KERNEL_H 10
#define DSCNN_STEM_KERNEL_W 4
#define DSCNN_STEM_PADDING_H 5
#define DSCNN_STEM_PADDING_W 1

// W8A8 quantization: per-tensor symmetric int8 activations
#define DSCNN_FEAT_IN_SCALE  5.9112064e-02f
#define DSCNN_FC_IN_SCALE    1.7292105e-01f

extern const char* const DSCNN_CLASSES[DSCNN_N_CLASSES];

// stem: shape=(172, 1, 10, 4) stride=(4, 2) pad=(5, 1) relu=True
extern const int8_t  stem_W[6880];
extern const int32_t stem_B32[172];
extern const float   stem_M[172];

// block0_dw: shape=(172, 1, 3, 3) stride=(1, 1) pad=(1, 1) relu=True
extern const int8_t  block0_dw_W[1548];
extern const int32_t block0_dw_B32[172];
extern const float   block0_dw_M[172];

// block0_pw: shape=(172, 172, 1, 1) stride=(1, 1) pad=(0, 0) relu=True
extern const int8_t  block0_pw_W[29584];
extern const int32_t block0_pw_B32[172];
extern const float   block0_pw_M[172];

// block1_dw: shape=(172, 1, 3, 3) stride=(1, 1) pad=(1, 1) relu=True
extern const int8_t  block1_dw_W[1548];
extern const int32_t block1_dw_B32[172];
extern const float   block1_dw_M[172];

// block1_pw: shape=(172, 172, 1, 1) stride=(1, 1) pad=(0, 0) relu=True
extern const int8_t  block1_pw_W[29584];
extern const int32_t block1_pw_B32[172];
extern const float   block1_pw_M[172];

// block2_dw: shape=(172, 1, 3, 3) stride=(1, 1) pad=(1, 1) relu=True
extern const int8_t  block2_dw_W[1548];
extern const int32_t block2_dw_B32[172];
extern const float   block2_dw_M[172];

// block2_pw: shape=(172, 172, 1, 1) stride=(1, 1) pad=(0, 0) relu=True
extern const int8_t  block2_pw_W[29584];
extern const int32_t block2_pw_B32[172];
extern const float   block2_pw_M[172];

// block3_dw: shape=(172, 1, 3, 3) stride=(1, 1) pad=(1, 1) relu=True
extern const int8_t  block3_dw_W[1548];
extern const int32_t block3_dw_B32[172];
extern const float   block3_dw_M[172];

// block3_pw: shape=(172, 172, 1, 1) stride=(1, 1) pad=(0, 0) relu=True
extern const int8_t  block3_pw_W[29584];
extern const int32_t block3_pw_B32[172];
extern const float   block3_pw_M[172];

// fc: shape=(4, 172)
extern const int8_t  fc_W[688];
extern const float   fc_S[4];      // per-output-channel weight scale
extern const float   fc_B[4];      // float bias (added in fp32)
